version: '3'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    container_name: school-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "5432"
    volumes:
      - PGdata:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    container_name: school-server
    expose:
      - "8000"
    env_file:
      - .env
    command: bash -c "alembic upgrade head &&  uvicorn main:app --host 0.0.0.0 --port 8000"

  nginx:
    restart: always
    container_name: school-nginx
    image: nginx:1.22.0-alpine
    depends_on:
      - server
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  PGdata:


