"""update models2

Revision ID: 856ad9c9ec30
Revises: dcc872d432dc
Create Date: 2023-04-03 00:02:22.611639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856ad9c9ec30'
down_revision = 'dcc872d432dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
