"""update models

Revision ID: dcc872d432dc
Revises: 17f9e3f3528d
Create Date: 2023-03-28 01:01:12.113399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc872d432dc'
down_revision = '17f9e3f3528d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('students', 'middle_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'middle_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('courses', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
